# scene
scene: gibson
scene_id: Walls
build_graph: true
load_texture: false
pybullet_load_texture: false
trav_map_type: no_obj
trav_map_resolution: 0.1
trav_map_erosion: 2
should_open_all_doors: true

# domain randomization
texture_randomization_freq: null
object_randomization_freq: null

# robot
robot: Turtlebot
is_discrete: false
velocity: 1.0

# task
task: social_nav_random
num_sqrt_meter_per_ped: 8
target_dist_min: 1.0
target_dist_max: 10.0
goal_format: cartesian
task_obs_dim: 4
waypoint_resolution: 1
orca_radius: 0.5
pedestrian_collision_threshold: 0.3

# orca
orca_neighbor_dist: 5
orca_time_horizon: 2.0
orca_time_horizon_obst: 2.0
orca_radius: 0.3
orca_max_speed: 0.5
pedestrian_goal_thresh: 0.3

# reward
reward_type: geodesic
success_reward: 10.0
potential_reward_weight: 1.0
collision_reward_weight: -0.1

# discount factor
discount_factor: 0.99

# termination condition
dist_tol: 0.36  # body width
max_step: 500
max_collisions_allowed: 500

# misc config
initial_pos_z_offset: 0.1
collision_ignore_link_a_ids: [1, 2, 3, 4]  # ignore collisions with these robot links

# sensor spec
output: [task_obs, scan, occupancy_grid]
# image
# ASUS Xtion PRO LIVE
# https://www.asus.com/us/3D-Sensor/Xtion_PRO_LIVE
fisheye: false
image_width: 160
image_height: 120
vertical_fov: 45
# depth
depth_low: 0.8
depth_high: 3.5


# scan
# Hokuyo URG-04LX-UG01
# https://www.hokuyo-aut.jp/search/single.php?serial=166
# n_horizontal_rays is originally 683, sub-sampled 1/3
n_horizontal_rays: 228
n_vertical_beams: 1
laser_linear_range: 5.6
laser_angular_range: 370.0
min_laser_dist: 0.05
laser_link_name: scan_link

# sensor noise
depth_noise_rate: 0.0
scan_noise_rate: 0.0

# visual objects
visual_object_at_initial_target_pos: false
target_visual_object_visible_to_agent: false
